/**
 * BrainFit contract witness implementations.
 *
 * Witnesses are the bridge between private state (stored only on the user's
 * device) and the Compact circuit. The secretKey is derived from the Lace
 * wallet and never sent to any server.
 *
 * @see brainfit.compact — `witness localSecretKey(): Bytes<32>;`
 */

import { type WitnessContext } from '@midnight-ntwrk/compact-runtime'

// ─── Private state type ───────────────────────────────────────────────────────

/**
 * The only private data needed by the BrainFit contract is the player's
 * 32-byte secret key. All other game data (scores, timing) remains off-chain.
 */
export type BrainFitPrivateState = {
  readonly secretKey: Uint8Array
}

/**
 * Create a new BrainFit private state from a raw secret key.
 * The key must be exactly 32 bytes (256 bits).
 */
export const createBrainFitPrivateState = (secretKey: Uint8Array): BrainFitPrivateState => {
  if (secretKey.length !== 32) {
    throw new Error(`Secret key must be 32 bytes, got ${secretKey.length}`)
  }
  return { secretKey }
}

// ─── Ledger type (generated by Compact compiler) ──────────────────────────────
// After running `compact compile src/brainfit.compact ./src/managed/brainfit`,
// the compiler generates a `Ledger` type in `managed/brainfit/contract/index.ts`.
// This import will resolve once the contract is compiled.

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type Ledger = any // Replaced by: import { Ledger } from './managed/brainfit/contract/index.js'

// ─── Witness implementations ──────────────────────────────────────────────────

/**
 * Witnesses object for the BrainFit contract.
 *
 * Each field maps a Compact `witness` declaration to its TypeScript
 * implementation. The implementation receives a `WitnessContext` containing
 * the current ledger state and private state, and returns a tuple of
 * `[newPrivateState, returnValue]`.
 *
 * `localSecretKey` reads the secret key from private state and returns it
 * to the circuit — it never touches the network or any logging system.
 */
export const witnesses = {
  localSecretKey: ({
    privateState,
  }: WitnessContext<Ledger, BrainFitPrivateState>): [BrainFitPrivateState, Uint8Array] => [
    privateState,
    privateState.secretKey,
  ],
}
